[package]
name = "miden-utils-indexing"
version = "0.34.0"
description = "Type-safe u32-indexed vector utilities for Miden"
readme = "README.md"
categories = ["development-tools", "no-std"]
keywords = ["miden", "indexing", "type-safe"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
arbitrary = ["std", "dep:proptest"]
default = ["std"]
std = ["proptest?/std"]

[dependencies]
# Required dependencies
miden-serde-utils.workspace = true
thiserror.workspace = true

# Optional dependencies
proptest = { workspace = true, optional = true }

[dev-dependencies]
miden-test-serialization-macros.workspace = true
proptest.workspace = true
