[package]
name = "miden-vm"
version = "0.34.0"
description = "Miden virtual machine"
documentation = "https://docs.rs/miden-vm"
readme = "README.md"
categories = ["cryptography", "emulators", "no-std"]
keywords = ["miden", "stark", "virtual-machine", "zkp"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[[bin]]
name = "miden-vm"
path = "src/main.rs"
bench = false
doctest = false
required-features = ["executable"]

[lib]
path = "src/lib.rs"
bench = false
doctest = false

[[bench]]
name = "build_trace"
required-features = ["internal"]
harness = false

[[bench]]
name = "program_execution_for_trace"
required-features = ["internal"]
harness = false

[[bench]]
name = "program_execution_fast"
required-features = ["internal"]
harness = false

[[bench]]
name = "deserialize_core_lib"
harness = false

[[bench]]
name = "deserialize_core_lib_debug_info"
harness = false

[[test]]
name = "miden-cli"
path = "tests/integration/main.rs"

[features]
arbitrary = ["std", "miden-assembly/testing", "miden-utils-testing/arbitrary"]
concurrent = ["miden-prover/concurrent", "std"]
default = ["std"]
executable = [
    "dep:clap",
    "dep:hex",
    "dep:tracing-subscriber",
    "internal",
    "serde",
    "std",
]
serde = ["dep:serde", "dep:serde_json"]
std = [
    "hex?/std",
    "miden-assembly/std",
    "miden-core-lib/std",
    "miden-processor/std",
    "miden-prover/std",
    "miden-verifier/std",
    "serde?/std",
    "serde_json?/std",
]
testing = ["arbitrary"]
# For internal use, not meant to be used by users
internal = ["dep:hex", "serde", "std"]

[dependencies]
# Miden dependencies
miden-assembly.workspace = true
miden-core.workspace = true
miden-processor.workspace = true
miden-prover.workspace = true
miden-mast-package.workspace = true
miden-core-lib.workspace = true
miden-verifier.workspace = true

# External dependencies
clap = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true, features = ["std", "env-filter"] }
tracing-forest = { workspace = true, optional = true, features = ["ansi", "smallvec"] }

[dev-dependencies]
assert_cmd = { version = "2.1" }
criterion = { workspace = true, features = ["async_tokio"] }
miden-assembly = { workspace = true, features = ["testing"] }
miden-processor = { workspace = true, features = ["testing"] }
miden-utils-testing.workspace = true
predicates = { version = "3.1" }
rand = { workspace = true, features = ["std", "thread_rng"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
walkdir.workspace = true
