[package]
name = "miden-processor"
version = "0.34.0"
description = "Miden VM processor"
documentation = "https://docs.rs/miden-processor"
readme = "README.md"
categories = ["emulators", "no-std"]
keywords = ["miden", "virtual-machine"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
exclude = ["*.snap"]

[lib]
bench = false
doctest = false

[features]
concurrent = ["std", "miden-air/concurrent"]
default = ["std"]
std = [
    "miden-core/std",
    "miden-debug-types/std",
    "miden-utils-diagnostics/std",
    "thiserror/std",
]
testing = ["miden-air/testing"]

[dependencies]
# Miden dependencies
miden-air.workspace = true
miden-core.workspace = true
miden-debug-types.workspace = true
miden-mast-package.workspace = true
miden-precompiles.workspace = true
miden-utils-diagnostics.workspace = true
miden-utils-indexing.workspace = true

# External dependencies
hashbrown.workspace = true
itertools.workspace = true
paste.workspace = true
rayon.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
miden-assembly = { workspace = true, features = ["testing"] }
miden-core = { workspace = true, features = ["arbitrary"] }
tracing = { workspace = true, features = ["std"] }
tracing-subscriber.workspace = true
miden-utils-testing.workspace = true
insta.workspace = true
pretty_assertions = { workspace = true, features = ["std"] }
proptest.workspace = true
rand = { workspace = true, features = ["std", "thread_rng"] }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
