[package]
name = "miden-constraint-compiler"
version = "0.34.0"
description = "Constraint compiler for Plonky3-based Miden AIRs."
documentation = "https://docs.rs/miden-constraint-compiler"
readme = "README.md"
categories = ["cryptography"]
keywords = ["air", "arithmetization", "compiler", "miden"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
miden-core = { workspace = true }
miden-crypto = { workspace = true }

[dev-dependencies]
miden-core = { workspace = true, features = ["std"] }
