[package]
edition.workspace      = true
license.workspace      = true
name                   = "miden-crypto-wycheproof-tests"
publish                = false
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lib]
doctest = false

[dev-dependencies]
ed25519-dalek       = { workspace = true }
hex                 = { features = ["alloc"], workspace = true }
k256                = { features = ["alloc", "ecdh", "ecdsa", "pkcs8"], workspace = true }
miden-crypto        = { default-features = false, features = ["std"], workspace = true }
wycheproof-ng-core  = { workspace = true }
wycheproof-ng-dh    = { workspace = true }
wycheproof-ng-ecdsa = { workspace = true }
wycheproof-ng-eddsa = { workspace = true }
x25519-dalek        = { features = ["static_secrets"], workspace = true }

[lints]
workspace = true
