import type { Config } from "@docusaurus/types";
import { existsSync } from "fs";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";

// If your content lives in docs/src, set DOCS_PATH='src'; else '.'
const DOCS_PATH = process.env.DOCS_PATH || (existsSync("src") ? "src" : ".");

const config: Config = {
  title: "Docs Dev Preview",
  url: "http://localhost:3000",
  baseUrl: "/",
  trailingSlash: false,

  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",

  // Minimal classic preset: docs only, autogenerated sidebars, same math plugins as prod
  presets: [
    [
      "classic",
      {
        docs: {
          path: DOCS_PATH, // '../docs' is implied because we are already inside docs/
          routeBasePath: "/", // mount docs at root for quick preview
          sidebarPath: "./sidebars.ts",
          remarkPlugins: [remarkMath],
          rehypePlugins: [rehypeKatex],
        },
        blog: false,
        theme: {
          // customCss: "./src/css/custom.css",
        },
      },
    ],
  ],

  stylesheets: [
    {
      href: "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      type: "text/css",
      integrity:
        "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      crossorigin: "anonymous",
    },
  ],

  themes: ["@docusaurus/theme-mermaid"],

  // enable mermaid diagrams and math support
  markdown: {
    mermaid: true,
  },
};
export default config;
