name: Trigger Aggregator Docs Rebuild

on:
  push:
    branches: [next]
    paths:
      - "docs/**"

permissions: {}

jobs:
  notify:
    runs-on: ubuntu-slim

    permissions: {}

    steps:
      - name: Send repository_dispatch to aggregator
        uses: peter-evans/repository-dispatch@b7037b45472c64c96f5a28a8c8443a7d5a237848
        with:
          # PAT (Personal Access Token) that grants permission to trigger the rebuild workflow at the docs repository
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          repository: ${{ vars.DOCS_AGGREGATOR_REPO }}
          event-type: rebuild
